### ISSUE TITLE
lumicube web on different port

### ISSUE THREAD

**Issue by nicolgit** [abstractfoundry/lumicube#9]
Hi guys, I'd like to use my lumicube (that have a Pi4 8Gb RAM inside) for more tasks, so I wondered how can I expose web server on a different port (i.e. 81).

can you help me?
N

**Comment by abstractfoundry** [comment]
Hi @nicolgit, if you run `sudo systemctl disable foundry-redirect.service` and restart your Raspberry Pi, our software will still be available on port 8686, and port 80 will be free for you to use however you want.
